all: locale/en_US/LC_MESSAGES/messages.mo locale/el_GR/LC_MESSAGES/messages.mo

locale/en_US/LC_MESSAGES/messages.mo: locale/en_US/LC_MESSAGES/messages.po
	msgfmt -o locale/en_US/LC_MESSAGES/messages.mo locale/en_US/LC_MESSAGES/messages.po

locale/el_GR/LC_MESSAGES/messages.mo: locale/el_GR/LC_MESSAGES/messages.po
	msgfmt -o locale/el_GR/LC_MESSAGES/messages.mo locale/el_GR/LC_MESSAGES/messages.po
